#!/bin/bash
for i in `seq 1 360`;
do
    ./rotate $1 $i $2 > img/$i.ppm;
    convert img/$i.ppm img/$i.gif;
    rm img/$i.ppm
    echo $i.gif done
done


gifsicle --delay 10 img/{1..180}.gif > master.gif
